### ISSUE TITLE
OverflowException in JsonValue.IsInteger is unnecessary

### ISSUE THREAD

**Issue by sharwell** [MarcosLopezC/LightJson#27]
You can use `unchecked((int)value)` to ensure this exception is not thrown even in builds that use checked arithmetic, making the exception handler unreachable.

🔗 Originally found in DotNetAnalyzers/StyleCopAnalyzers#2406

**Comment by MarcosLopezC** [comment]
@sharwell 

If `value` overflows when converting to `int` in an unchecked context then the value of `(int)value` is undefined, according to the C# language spec ([§13.2.1](https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf#page=160)).

Instead, I think this is a most robust solution:

```
(value % 1 == 0) && (value >= Int32.MinValue) && (value <= Int32.MaxValue)
```

**Comment by sharwell** [comment]
Interesting info, I didn't realize that.

:memo: For those wondering, this interesting language in the spec applies only for conversion of `double` or `float` to an integral type. For all the other possible numeric conversions, the result *is* defined by the spec. Also note that the result is unspecified (Annex B.3) as opposed to undefined (Annex B.1).

**Comment by sharwell** [comment]
@MarcosLopezC I would imagine this would be faster:

```
(value >= int.MinValue && value <= int.MaxValue && unchecked((int)value) == value)
```

**Comment by MarcosLopezC** [comment]
@sharwell 

I did a quick benchmark and I didn't find a significant difference in performance between the two expressions. I would prefer to avoid conversions at all for this.

**Comment by sharwell** [comment]
You can avoid conversions by declaring two constants:

```csharp
private const double Int32MaxValueAsDouble = int.MaxValue;
private const double Int32MinValueAsDouble = int.MinValue;
```

The problem for us was the inability to cover the indicated lines of code with tests. There are a few cases where this is acceptable, including the following:

* Race conditions where we can't ever guarantee coverage
* Code which would be less efficient or notably expressive if we were to modify it to allow full coverage

However, this case did not meet the above. During analysis we determined that the code was fully unreachable in our code base, and found a way to guarantee that it remains unreachable regardless of the code base where it appears.

**Comment by MarcosLopezC** [comment]
@sharwell 

I'm still a little confused. Let's do this: check out the changes in this commit (3ccc8d4924d9baa723f75f368d6493c36a8cc04b) and let me know if this fixes your issue.

When I was saying that I prefer to avoid conversion I meant that I prefer this:

```
value % 1 == 0
```

to this:

```
unchecked((int)value) == value)
```

**Comment by sharwell** [comment]
Why are you trying to avoid the cast?

**Comment by MarcosLopezC** [comment]
I think `value % 1 == 0` better expresses the intent. And I still don't see the need for `unchecked((int)value) == value)` given the other, shorter alternative. But if you can convince me using `unchecked((int)value) == value)` is better, then we can go with that.

**Comment by sharwell** [comment]
@MarcosLopezC It doesn't particularly matter one way or the other to me. I was mostly curious. My instinct to go with the conversion approach is that's the one that made more sense (re correctness) in my head, but what makes more sense to me might be more confusing to another.

**Comment by MarcosLopezC** [comment]
@sharwell I have asked a few of my colleagues and it seems your approach makes sense to them immediately. I guess not everyone is that familiar with modular operations on floating point numbers. For the sake of clarity, I will use your approach.
