### ISSUE TITLE
JsonValue.Parse cannot parse certain numbers

### ISSUE THREAD

**Issue by sharwell** [MarcosLopezC/LightJson#29]
Examples of numbers which fail:

* `JsonValue.Parse("1")`
* `JsonValue.Parse("1.0")`

🔗 Originally found in DotNetAnalyzers/StyleCopAnalyzers#2406

**Comment by MarcosLopezC** [comment]
This issue is fixed in commit d600918bb6edf884cc705de992e6c86a5d2f26e3.
