### ISSUE TITLE
JsonValue.Equals does not handle non-null types correctly

### ISSUE THREAD

**Issue by sharwell** [MarcosLopezC/LightJson#30]
The following both return true, but should not:

* `JsonValue.Null.Equals(1)`
* `JsonValue.Null.Equals(new Exception())`

:link: Originally found in DotNetAnalyzers/StyleCopAnalyzers#2406

**Comment by MarcosLopezC** [comment]
This issue was fixed in commit 8dad2102cc025c48f2d25552fe99dd8caeee03ae.
