### ISSUE TITLE
Failure to parse JSON object where value matches an earlier key

### ISSUE THREAD

**Issue by sharwell** [MarcosLopezC/LightJson#31]
`JsonValue.Parse` will fail to parse the following:

```json
{
  "x": "value",
  "value": "anything"
}
```

On a related note, the exception thrown for cases where the keys *do* collide is currently incorrect.

:link: Both issues above originally found in DotNetAnalyzers/StyleCopAnalyzers#2406

**Comment by MarcosLopezC** [comment]
This issue was fixed in commit bdf18f5f754b8de5e39c9ec5cf160b33227850a7.
