### ISSUE TITLE
JsonObject.Rename fails when old and new name are the same

### ISSUE THREAD

**Issue by sharwell** [MarcosLopezC/LightJson#32]
When the old and new keys are the same, `JsonObject.Rename` will remove the key rather than return without making changes.

```csharp
var obj = new JsonObject { ["x"] = "value" };
obj.Rename("x", "x");
Assert.True(obj.ContainsKey("x")); // This currently fails
```

:link: This was originally found in DotNetAnalyzers/StyleCopAnalyzers#2406.

**Comment by MarcosLopezC** [comment]
This issue was fixed in commit ed5b767ab01fe719b733783493a6d77f79eb9b26.
