### ISSUE TITLE
Incorrect exception thrown for 'null' passed to JsonArray constructor

### ISSUE THREAD

**Issue by sharwell** [MarcosLopezC/LightJson#33]
Code:

```csharp
new JsonArray(default(JsonValue[]));

// Or equivalently:
new JsonArray((JsonValue[])null);
```

Expected exception: `ArgumentNullException`, with `paramName` set to `values`

Actual exception: `NullReferenceException`

:link: Originally found in DotNetAnalyzers/StyleCopAnalyzers#2406.

**Comment by MarcosLopezC** [comment]
This issue is fixed by commit e0dbb54b8bde3aa037dc0d87a2bd19430e512f30.
