### ISSUE TITLE
JsonWriter.IsValidNumber is not used

### ISSUE THREAD

**Issue by sharwell** [MarcosLopezC/LightJson#36]
I noticed during work on DotNetAnalyzers/StyleCopAnalyzers#2406 that the following two items are not used:

* `JsonWriter.IsValidNumber`
* `JsonSerializationException.InvalidNumber`

**Comment by MarcosLopezC** [comment]
Internally LightJson uses `double` to represent Json numbers. However, not all `double` values are valid Json numbers. For example:
- `double.NaN`
- `double.PositiveInfinity`
- `double.NegativeInfinity`

`JsonWriter` is supposed to make sure you can't write a Json Number with those invalid values.

**Comment by sharwell** [comment]
That was my guess, which is why I didn't remove it from our copy. I'm waiting to see how you implement this functionality and will cherry-pick it then. 👍

**Comment by MarcosLopezC** [comment]
Fixed in d69bc4a02b8faba631af23f87bc9a396bba1de2a.
