### ISSUE TITLE
Request to decrease target framework

### ISSUE THREAD

**Issue by bjornhellander** [MarcosLopezC/LightJson#46]
This project is currently targeting .NET Standard 2.1, which makes it unusable in any application targeting .NET Framework. I request a decrease in the target framework to .NET Standard 2.0 instead, to make it usable in more applications.

**Comment by MarcosLopezC** [comment]
Looks good. I'll added to the `v0.5.0` release sometime next week. Just out of curiosity, though, what version of .NET Framework are you using that needs .NET Standard 2.0?

**Comment by bjornhellander** [comment]
.NET Framework 4.8. Still lots of legacy applications out there :-)

But as I wrote previously, there is not a single .NET Framework version that supports .NET Standard 2.1. It was a bit of an odd one. Microsoft recommends 2.0 for .NET Standard libraries (https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

**Comment by bjornhellander** [comment]
I looks like I force pushed an update after you answered. I had made a mistake that I think would have resulted in an exception when parsing a read-only file, but it should be fixed now.

**Comment by bjornhellander** [comment]
Updated again, with a test case this time, just to make sure that read-only files can be handled ok
